import type { Platform, StrategyTier } from "@shared/schema";

export const platforms: Platform[] = [
  {
    id: "claude-sonnet",
    name: "Claude (Sonnet 4)",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Best-in-class for coding, analysis, and nuanced reasoning with superior safety guardrails.",
    marketShare: "12%",
    pricing: "$20/user/month",
    contextWindow: "200K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Developers, Analysts, Researchers",
    capabilities: {
      codeGeneration: 10,
      reasoning: 10,
      languageUnderstanding: 9,
      multimodal: 8,
      toolUse: 9,
      speed: 8,
      costEfficiency: 8,
      enterpriseFeatures: 9,
      developerExperience: 9,
      documentation: 9,
      vision: 9,
      audio: 3,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 10,
      onPremOption: 5,
      slaAvailability: 9,
      contextRecall: 9,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#D97706",
  },
  {
    id: "claude-opus",
    name: "Claude (Opus 4)",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Most capable model for complex reasoning, extended thinking, and enterprise-critical tasks.",
    marketShare: "8%",
    pricing: "$75/user/month",
    contextWindow: "200K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR", "FedRAMP"],
    targetUsers: "Enterprise, Research Labs, Legal",
    capabilities: {
      codeGeneration: 10,
      reasoning: 10,
      languageUnderstanding: 10,
      multimodal: 9,
      toolUse: 10,
      speed: 5,
      costEfficiency: 4,
      enterpriseFeatures: 10,
      developerExperience: 9,
      documentation: 9,
      vision: 9,
      audio: 4,
      functionCalling: 10,
      jsonReliability: 10,
      dataPrivacy: 10,
      onPremOption: 6,
      slaAvailability: 10,
      contextRecall: 10,
      timeToFirstToken: 5,
      tokensPerSecond: 5,
    },
    logoColor: "#D97706",
  },
  {
    id: "chatgpt-enterprise",
    name: "ChatGPT Enterprise",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Most widely adopted with excellent general-purpose capabilities and strong ecosystem.",
    marketShare: "38%",
    pricing: "$60/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Enterprise Teams, Knowledge Workers",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 9,
      toolUse: 9,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
      vision: 9,
      audio: 8,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 7,
      onPremOption: 3,
      slaAvailability: 9,
      contextRecall: 8,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#10A37F",
  },
  {
    id: "gemini-advanced",
    name: "Gemini Advanced",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Excellent for research with massive context window and deep Google ecosystem integration.",
    marketShare: "15%",
    pricing: "$20/user/month",
    contextWindow: "1M tokens",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Researchers, Google Workspace Users",
    capabilities: {
      codeGeneration: 8,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 10,
      toolUse: 8,
      speed: 9,
      costEfficiency: 9,
      enterpriseFeatures: 8,
      developerExperience: 7,
      documentation: 8,
      vision: 10,
      audio: 9,
      functionCalling: 8,
      jsonReliability: 7,
      dataPrivacy: 6,
      onPremOption: 4,
      slaAvailability: 8,
      contextRecall: 10,
      timeToFirstToken: 7,
      tokensPerSecond: 8,
    },
    logoColor: "#4285F4",
  },
  {
    id: "microsoft-copilot",
    name: "Microsoft Copilot",
    category: "Enterprise",
    priority: "Tier 1",
    verdict: "Seamless Microsoft 365 integration for enterprise productivity at scale.",
    marketShare: "18%",
    pricing: "$30/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR", "FedRAMP"],
    targetUsers: "Microsoft 365 Users, Enterprise",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 8,
      toolUse: 9,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 7,
      documentation: 8,
      vision: 8,
      audio: 7,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 8,
      onPremOption: 8,
      slaAvailability: 10,
      contextRecall: 7,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#00A4EF",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "Specialized",
    priority: "Tier 1",
    verdict: "Industry-leading code completion and generation for software developers.",
    marketShare: "8%",
    pricing: "$10-20/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2"],
    targetUsers: "Software Developers",
    capabilities: {
      codeGeneration: 10,
      reasoning: 7,
      languageUnderstanding: 7,
      multimodal: 3,
      toolUse: 8,
      speed: 9,
      costEfficiency: 9,
      enterpriseFeatures: 7,
      developerExperience: 10,
      documentation: 8,
      vision: 2,
      audio: 1,
      functionCalling: 6,
      jsonReliability: 7,
      dataPrivacy: 7,
      onPremOption: 5,
      slaAvailability: 8,
      contextRecall: 6,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#24292E",
  },
  {
    id: "mistral-large",
    name: "Mistral Large 2",
    category: "Foundation",
    priority: "Tier 1",
    verdict: "Top-tier European AI with strong coding, multilingual support, and EU data sovereignty.",
    marketShare: "4%",
    pricing: "$15/user/month",
    contextWindow: "128K tokens",
    compliance: ["GDPR", "SOC2"],
    targetUsers: "Developers, EU Enterprises, Multilingual Teams",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 6,
      toolUse: 9,
      speed: 9,
      costEfficiency: 9,
      enterpriseFeatures: 8,
      developerExperience: 8,
      documentation: 7,
      vision: 5,
      audio: 2,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 10,
      onPremOption: 8,
      slaAvailability: 7,
      contextRecall: 8,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#FF7000",
  },
  {
    id: "llama-3",
    name: "Meta Llama 3.1 (405B)",
    category: "Developer",
    priority: "Tier 1",
    verdict: "Best open-source model with full self-hosting capability and zero data sharing.",
    marketShare: "6%",
    pricing: "Free (Self-hosted)",
    contextWindow: "128K tokens",
    compliance: ["Self-managed"],
    targetUsers: "ML Engineers, Privacy-focused Enterprises",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 9,
      multimodal: 5,
      toolUse: 7,
      speed: 7,
      costEfficiency: 10,
      enterpriseFeatures: 5,
      developerExperience: 7,
      documentation: 8,
      vision: 4,
      audio: 2,
      functionCalling: 7,
      jsonReliability: 7,
      dataPrivacy: 10,
      onPremOption: 10,
      slaAvailability: 3,
      contextRecall: 7,
      timeToFirstToken: 7,
      tokensPerSecond: 7,
    },
    logoColor: "#0668E1",
  },
  {
    id: "grok-2",
    name: "xAI Grok 2",
    category: "Foundation",
    priority: "Tier 2",
    verdict: "Real-time knowledge with X (Twitter) integration and minimal content restrictions.",
    marketShare: "2%",
    pricing: "$25/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2"],
    targetUsers: "Researchers, Analysts, Social Media Teams",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 7,
      speed: 9,
      costEfficiency: 7,
      enterpriseFeatures: 6,
      developerExperience: 7,
      documentation: 6,
      vision: 7,
      audio: 5,
      functionCalling: 7,
      jsonReliability: 7,
      dataPrivacy: 5,
      onPremOption: 2,
      slaAvailability: 6,
      contextRecall: 8,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#1DA1F2",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    category: "Developer",
    priority: "Tier 2",
    verdict: "Exceptional value with GPT-4 level performance at fraction of cost.",
    marketShare: "3%",
    pricing: "$0.14/M tokens",
    contextWindow: "128K tokens",
    compliance: ["GDPR"],
    targetUsers: "Cost-conscious Developers, Startups",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 8,
      multimodal: 6,
      toolUse: 8,
      speed: 8,
      costEfficiency: 10,
      enterpriseFeatures: 4,
      developerExperience: 7,
      documentation: 6,
      vision: 6,
      audio: 2,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 5,
      onPremOption: 6,
      slaAvailability: 4,
      contextRecall: 8,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#4A90D9",
  },
  {
    id: "groq",
    name: "Groq LPU",
    category: "Developer",
    priority: "Tier 2",
    verdict: "Fastest inference engine with 10x speed advantage for latency-critical applications.",
    marketShare: "1%",
    pricing: "Pay-per-token",
    contextWindow: "128K tokens",
    compliance: ["SOC2"],
    targetUsers: "Real-time Apps, Gaming, Voice Assistants",
    capabilities: {
      codeGeneration: 7,
      reasoning: 7,
      languageUnderstanding: 8,
      multimodal: 5,
      toolUse: 7,
      speed: 10,
      costEfficiency: 8,
      enterpriseFeatures: 5,
      developerExperience: 7,
      documentation: 6,
      vision: 4,
      audio: 3,
      functionCalling: 7,
      jsonReliability: 8,
      dataPrivacy: 7,
      onPremOption: 4,
      slaAvailability: 6,
      contextRecall: 7,
      timeToFirstToken: 10,
      tokensPerSecond: 10,
    },
    logoColor: "#FF4500",
  },
  {
    id: "perplexity-pro",
    name: "Perplexity Pro",
    category: "Specialized",
    priority: "Tier 2",
    verdict: "Best-in-class research assistant with real-time web search and citations.",
    marketShare: "3%",
    pricing: "$20/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Researchers, Analysts",
    capabilities: {
      codeGeneration: 6,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 9,
      speed: 9,
      costEfficiency: 8,
      enterpriseFeatures: 6,
      developerExperience: 7,
      documentation: 7,
      vision: 7,
      audio: 3,
      functionCalling: 7,
      jsonReliability: 7,
      dataPrivacy: 7,
      onPremOption: 2,
      slaAvailability: 7,
      contextRecall: 8,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#20808D",
  },
  {
    id: "anthropic-api",
    name: "Anthropic API",
    category: "Developer",
    priority: "Tier 2",
    verdict: "Direct API access to Claude models with flexible pricing for custom integrations.",
    marketShare: "5%",
    pricing: "Pay-per-token",
    contextWindow: "200K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Developers, API Integrators",
    capabilities: {
      codeGeneration: 10,
      reasoning: 10,
      languageUnderstanding: 9,
      multimodal: 8,
      toolUse: 9,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 7,
      developerExperience: 9,
      documentation: 9,
      vision: 9,
      audio: 3,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 10,
      onPremOption: 5,
      slaAvailability: 8,
      contextRecall: 9,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#D97706",
  },
  {
    id: "openai-api",
    name: "OpenAI API",
    category: "Developer",
    priority: "Tier 2",
    verdict: "Most extensive API ecosystem with GPT-4 and specialized models for any use case.",
    marketShare: "25%",
    pricing: "Pay-per-token",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Developers, Enterprises",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 9,
      toolUse: 9,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 8,
      developerExperience: 9,
      documentation: 10,
      vision: 9,
      audio: 9,
      functionCalling: 10,
      jsonReliability: 9,
      dataPrivacy: 6,
      onPremOption: 3,
      slaAvailability: 9,
      contextRecall: 8,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#10A37F",
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Multi-model platform deeply integrated with AWS services for enterprise scale.",
    marketShare: "4%",
    pricing: "Variable",
    contextWindow: "Variable",
    compliance: ["SOC2", "HIPAA", "FedRAMP"],
    targetUsers: "AWS Customers, Enterprise",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 8,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 7,
      documentation: 8,
      vision: 7,
      audio: 6,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 9,
      onPremOption: 9,
      slaAvailability: 10,
      contextRecall: 7,
      timeToFirstToken: 7,
      tokensPerSecond: 7,
    },
    logoColor: "#FF9900",
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "OpenAI models with Azure enterprise security, compliance, and regional data residency.",
    marketShare: "6%",
    pricing: "Variable",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "HIPAA", "FedRAMP", "GDPR"],
    targetUsers: "Azure Customers, Government",
    capabilities: {
      codeGeneration: 9,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 9,
      toolUse: 8,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
      vision: 9,
      audio: 8,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 9,
      onPremOption: 9,
      slaAvailability: 10,
      contextRecall: 8,
      timeToFirstToken: 7,
      tokensPerSecond: 7,
    },
    logoColor: "#0078D4",
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "Developer",
    priority: "Tier 3",
    verdict: "Specialized NLP platform with excellent embedding models and enterprise search.",
    marketShare: "2%",
    pricing: "Pay-per-token",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "NLP Developers, Search Teams",
    capabilities: {
      codeGeneration: 6,
      reasoning: 7,
      languageUnderstanding: 9,
      multimodal: 4,
      toolUse: 6,
      speed: 9,
      costEfficiency: 8,
      enterpriseFeatures: 7,
      developerExperience: 8,
      documentation: 7,
      vision: 3,
      audio: 2,
      functionCalling: 7,
      jsonReliability: 8,
      dataPrivacy: 8,
      onPremOption: 7,
      slaAvailability: 7,
      contextRecall: 8,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#39594D",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "Developer",
    priority: "Tier 3",
    verdict: "Open model hub with thousands of models and excellent fine-tuning capabilities.",
    marketShare: "3%",
    pricing: "Free-Variable",
    contextWindow: "Variable",
    compliance: ["GDPR"],
    targetUsers: "ML Engineers, Researchers",
    capabilities: {
      codeGeneration: 7,
      reasoning: 7,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 6,
      speed: 7,
      costEfficiency: 10,
      enterpriseFeatures: 5,
      developerExperience: 8,
      documentation: 9,
      vision: 7,
      audio: 6,
      functionCalling: 5,
      jsonReliability: 6,
      dataPrivacy: 9,
      onPremOption: 10,
      slaAvailability: 4,
      contextRecall: 6,
      timeToFirstToken: 6,
      tokensPerSecond: 6,
    },
    logoColor: "#FFD21E",
  },
  {
    id: "jasper",
    name: "Jasper",
    category: "Specialized",
    priority: "Tier 2",
    verdict: "Purpose-built for marketing teams with brand voice training and campaign tools.",
    marketShare: "2%",
    pricing: "$49/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Marketing Teams, Content Creators",
    capabilities: {
      codeGeneration: 2,
      reasoning: 6,
      languageUnderstanding: 8,
      multimodal: 6,
      toolUse: 7,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 7,
      developerExperience: 5,
      documentation: 7,
      vision: 5,
      audio: 2,
      functionCalling: 4,
      jsonReliability: 5,
      dataPrivacy: 7,
      onPremOption: 2,
      slaAvailability: 7,
      contextRecall: 6,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#FF5A5F",
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    category: "Specialized",
    priority: "Tier 3",
    verdict: "Sales-focused copywriting platform with workflow automation for GTM teams.",
    marketShare: "1%",
    pricing: "$49/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Sales Teams, Marketers",
    capabilities: {
      codeGeneration: 1,
      reasoning: 5,
      languageUnderstanding: 7,
      multimodal: 4,
      toolUse: 6,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 6,
      developerExperience: 5,
      documentation: 6,
      vision: 3,
      audio: 1,
      functionCalling: 4,
      jsonReliability: 5,
      dataPrivacy: 6,
      onPremOption: 1,
      slaAvailability: 6,
      contextRecall: 5,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#7C3AED",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: "Productivity",
    priority: "Tier 2",
    verdict: "Seamlessly integrated AI for knowledge management within the Notion ecosystem.",
    marketShare: "2%",
    pricing: "$10/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Notion Users, Knowledge Workers",
    capabilities: {
      codeGeneration: 4,
      reasoning: 6,
      languageUnderstanding: 7,
      multimodal: 5,
      toolUse: 8,
      speed: 8,
      costEfficiency: 9,
      enterpriseFeatures: 6,
      developerExperience: 5,
      documentation: 7,
      vision: 4,
      audio: 2,
      functionCalling: 5,
      jsonReliability: 6,
      dataPrivacy: 7,
      onPremOption: 2,
      slaAvailability: 7,
      contextRecall: 7,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#000000",
  },
  {
    id: "slack-ai",
    name: "Slack AI",
    category: "Productivity",
    priority: "Tier 3",
    verdict: "Channel summaries and thread insights for teams already living in Slack.",
    marketShare: "1%",
    pricing: "$10/user/month",
    contextWindow: "N/A",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "Slack Users, Team Collaboration",
    capabilities: {
      codeGeneration: 2,
      reasoning: 5,
      languageUnderstanding: 7,
      multimodal: 3,
      toolUse: 7,
      speed: 8,
      costEfficiency: 8,
      enterpriseFeatures: 7,
      developerExperience: 4,
      documentation: 6,
      vision: 2,
      audio: 3,
      functionCalling: 5,
      jsonReliability: 6,
      dataPrivacy: 8,
      onPremOption: 3,
      slaAvailability: 8,
      contextRecall: 7,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#4A154B",
  },
  {
    id: "glean",
    name: "Glean",
    category: "Enterprise",
    priority: "Tier 1",
    verdict: "Enterprise-wide AI search across all systems with permission-aware retrieval.",
    marketShare: "3%",
    pricing: "$15-30/user/month",
    contextWindow: "Variable",
    compliance: ["SOC2", "GDPR", "HIPAA"],
    targetUsers: "Knowledge Workers, Enterprise Teams",
    capabilities: {
      codeGeneration: 4,
      reasoning: 8,
      languageUnderstanding: 9,
      multimodal: 6,
      toolUse: 9,
      speed: 9,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 7,
      documentation: 8,
      vision: 5,
      audio: 3,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 9,
      onPremOption: 7,
      slaAvailability: 9,
      contextRecall: 10,
      timeToFirstToken: 9,
      tokensPerSecond: 8,
    },
    logoColor: "#6366F1",
  },
  {
    id: "vertex-ai",
    name: "Google Vertex AI",
    category: "Enterprise",
    priority: "Tier 1",
    verdict: "Google Cloud's unified AI platform with agent orchestration and enterprise governance.",
    marketShare: "5%",
    pricing: "Pay-per-use",
    contextWindow: "1M tokens",
    compliance: ["SOC2", "HIPAA", "FedRAMP", "GDPR"],
    targetUsers: "GCP Customers, ML Engineers",
    capabilities: {
      codeGeneration: 8,
      reasoning: 9,
      languageUnderstanding: 9,
      multimodal: 10,
      toolUse: 9,
      speed: 8,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
      vision: 10,
      audio: 9,
      functionCalling: 9,
      jsonReliability: 8,
      dataPrivacy: 9,
      onPremOption: 8,
      slaAvailability: 10,
      contextRecall: 9,
      timeToFirstToken: 7,
      tokensPerSecond: 8,
    },
    logoColor: "#4285F4",
  },
  {
    id: "salesforce-agentforce",
    name: "Salesforce Agentforce",
    category: "Enterprise",
    priority: "Tier 1",
    verdict: "CRM-native AI agents for sales automation and customer workflows.",
    marketShare: "4%",
    pricing: "$50/agent/month",
    contextWindow: "Variable",
    compliance: ["SOC2", "HIPAA", "GDPR"],
    targetUsers: "Salesforce Users, Sales Teams",
    capabilities: {
      codeGeneration: 3,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 5,
      toolUse: 10,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 7,
      documentation: 8,
      vision: 4,
      audio: 5,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 9,
      onPremOption: 6,
      slaAvailability: 10,
      contextRecall: 8,
      timeToFirstToken: 8,
      tokensPerSecond: 8,
    },
    logoColor: "#00A1E0",
  },
  {
    id: "databricks",
    name: "Databricks",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Unified data and AI platform with lakehouse architecture for enterprise ML.",
    marketShare: "4%",
    pricing: "Variable",
    contextWindow: "Variable",
    compliance: ["SOC2", "HIPAA", "FedRAMP", "GDPR"],
    targetUsers: "Data Engineers, ML Teams, Enterprise",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 6,
      toolUse: 9,
      speed: 8,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
      vision: 5,
      audio: 4,
      functionCalling: 8,
      jsonReliability: 9,
      dataPrivacy: 10,
      onPremOption: 9,
      slaAvailability: 10,
      contextRecall: 8,
      timeToFirstToken: 7,
      tokensPerSecond: 8,
    },
    logoColor: "#FF3621",
  },
  {
    id: "writer",
    name: "Writer",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Enterprise content generation with brand governance and AI agents.",
    marketShare: "2%",
    pricing: "$18/user/month",
    contextWindow: "128K tokens",
    compliance: ["SOC2", "GDPR", "HIPAA"],
    targetUsers: "Marketing Teams, Enterprise Content",
    capabilities: {
      codeGeneration: 3,
      reasoning: 7,
      languageUnderstanding: 9,
      multimodal: 6,
      toolUse: 8,
      speed: 9,
      costEfficiency: 7,
      enterpriseFeatures: 9,
      developerExperience: 7,
      documentation: 8,
      vision: 5,
      audio: 3,
      functionCalling: 7,
      jsonReliability: 8,
      dataPrivacy: 9,
      onPremOption: 5,
      slaAvailability: 8,
      contextRecall: 8,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#5046E5",
  },
  {
    id: "together-ai",
    name: "Together AI",
    category: "Developer",
    priority: "Tier 2",
    verdict: "High-performance inference platform with 2x+ speedups for open models.",
    marketShare: "2%",
    pricing: "Pay-per-token",
    contextWindow: "Variable",
    compliance: ["SOC2", "GDPR"],
    targetUsers: "ML Engineers, Developers",
    capabilities: {
      codeGeneration: 8,
      reasoning: 8,
      languageUnderstanding: 8,
      multimodal: 7,
      toolUse: 7,
      speed: 10,
      costEfficiency: 9,
      enterpriseFeatures: 6,
      developerExperience: 9,
      documentation: 8,
      vision: 6,
      audio: 4,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 8,
      onPremOption: 6,
      slaAvailability: 7,
      contextRecall: 8,
      timeToFirstToken: 10,
      tokensPerSecond: 10,
    },
    logoColor: "#00D4AA",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "Specialized",
    priority: "Tier 1",
    verdict: "AI-native IDE transforming developer productivity with deep code understanding.",
    marketShare: "3%",
    pricing: "$20/user/month",
    contextWindow: "Variable",
    compliance: ["SOC2"],
    targetUsers: "Software Developers, Engineering Teams",
    capabilities: {
      codeGeneration: 10,
      reasoning: 9,
      languageUnderstanding: 8,
      multimodal: 4,
      toolUse: 9,
      speed: 9,
      costEfficiency: 8,
      enterpriseFeatures: 7,
      developerExperience: 10,
      documentation: 7,
      vision: 3,
      audio: 1,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 7,
      onPremOption: 4,
      slaAvailability: 7,
      contextRecall: 9,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#000000",
  },
  {
    id: "dataiku",
    name: "Dataiku",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Enterprise data science platform with AI-powered analytics and governance.",
    marketShare: "2%",
    pricing: "Enterprise pricing",
    contextWindow: "Variable",
    compliance: ["SOC2", "GDPR", "HIPAA"],
    targetUsers: "Data Scientists, Analysts, Enterprise",
    capabilities: {
      codeGeneration: 7,
      reasoning: 8,
      languageUnderstanding: 7,
      multimodal: 6,
      toolUse: 9,
      speed: 7,
      costEfficiency: 6,
      enterpriseFeatures: 10,
      developerExperience: 8,
      documentation: 9,
      vision: 5,
      audio: 3,
      functionCalling: 7,
      jsonReliability: 8,
      dataPrivacy: 9,
      onPremOption: 10,
      slaAvailability: 9,
      contextRecall: 7,
      timeToFirstToken: 7,
      tokensPerSecond: 7,
    },
    logoColor: "#2AB1AC",
  },
  {
    id: "cognigy",
    name: "Cognigy",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Multilingual conversational AI platform supporting 100+ languages.",
    marketShare: "1%",
    pricing: "Enterprise pricing",
    contextWindow: "Variable",
    compliance: ["SOC2", "GDPR", "HIPAA"],
    targetUsers: "Customer Service, Contact Centers",
    capabilities: {
      codeGeneration: 3,
      reasoning: 7,
      languageUnderstanding: 10,
      multimodal: 7,
      toolUse: 9,
      speed: 9,
      costEfficiency: 7,
      enterpriseFeatures: 9,
      developerExperience: 7,
      documentation: 8,
      vision: 4,
      audio: 9,
      functionCalling: 8,
      jsonReliability: 8,
      dataPrivacy: 9,
      onPremOption: 8,
      slaAvailability: 9,
      contextRecall: 8,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#FF6B35",
  },
  {
    id: "moveworks",
    name: "Moveworks",
    category: "Enterprise",
    priority: "Tier 2",
    verdict: "Autonomous IT/HR support automation with enterprise system orchestration.",
    marketShare: "2%",
    pricing: "Enterprise pricing",
    contextWindow: "Variable",
    compliance: ["SOC2", "GDPR", "HIPAA"],
    targetUsers: "IT Teams, HR, Enterprise Support",
    capabilities: {
      codeGeneration: 4,
      reasoning: 8,
      languageUnderstanding: 9,
      multimodal: 5,
      toolUse: 10,
      speed: 9,
      costEfficiency: 7,
      enterpriseFeatures: 10,
      developerExperience: 6,
      documentation: 8,
      vision: 4,
      audio: 6,
      functionCalling: 9,
      jsonReliability: 9,
      dataPrivacy: 9,
      onPremOption: 7,
      slaAvailability: 10,
      contextRecall: 8,
      timeToFirstToken: 9,
      tokensPerSecond: 9,
    },
    logoColor: "#6C5CE7",
  },
];

export const strategyTiers: StrategyTier[] = [
  {
    tier: 1,
    name: "Foundation",
    description: "Core platforms for broad enterprise adoption with proven ROI",
    platforms: ["claude-sonnet", "claude-opus", "chatgpt-enterprise", "github-copilot", "microsoft-copilot", "gemini-advanced", "mistral-large", "llama-3", "glean", "vertex-ai", "salesforce-agentforce", "cursor"],
    rationale: "Tier 1 platforms offer the best balance of capability, enterprise features, and market maturity. Start here for maximum impact with minimal risk.",
  },
  {
    tier: 2,
    name: "Specialization",
    description: "Domain-specific tools for targeted use cases and power users",
    platforms: ["perplexity-pro", "jasper", "notion-ai", "anthropic-api", "openai-api", "aws-bedrock", "azure-openai", "grok-2", "deepseek-v3", "groq", "databricks", "writer", "together-ai", "dataiku", "cognigy", "moveworks"],
    rationale: "After establishing foundation tools, add specialized platforms for specific workflows like research, marketing, and custom integrations.",
  },
  {
    tier: 3,
    name: "Advanced",
    description: "Cutting-edge and experimental platforms for innovation teams",
    platforms: ["cohere", "huggingface", "copy-ai", "slack-ai"],
    rationale: "Advanced platforms for teams with mature AI adoption seeking fine-tuning, custom models, or experimental capabilities.",
  },
];

export const capabilityLabels: Record<keyof Platform["capabilities"], string> = {
  codeGeneration: "Code Generation",
  reasoning: "Reasoning",
  languageUnderstanding: "Language Understanding",
  multimodal: "Multimodal",
  toolUse: "Tool Use",
  speed: "Speed",
  costEfficiency: "Cost Efficiency",
  enterpriseFeatures: "Enterprise Features",
  developerExperience: "Developer Experience",
  documentation: "Documentation",
  vision: "Vision & OCR",
  audio: "Audio Processing",
  functionCalling: "Function Calling",
  jsonReliability: "JSON Reliability",
  dataPrivacy: "Data Privacy",
  onPremOption: "On-Prem/VPC",
  slaAvailability: "SLA Availability",
  contextRecall: "Context Recall",
  timeToFirstToken: "Time to First Token",
  tokensPerSecond: "Tokens Per Second",
};

export const matrixFeatures = [
  { category: "Core Capabilities", features: ["codeGeneration", "reasoning", "languageUnderstanding", "multimodal", "toolUse", "speed"] },
  { category: "Enterprise & Cost", features: ["costEfficiency", "enterpriseFeatures", "developerExperience", "documentation"] },
  { category: "Vision & Audio", features: ["vision", "audio"] },
  { category: "API & Tools", features: ["functionCalling", "jsonReliability"] },
  { category: "Security & Compliance", features: ["dataPrivacy", "onPremOption", "slaAvailability"] },
  { category: "Performance", features: ["contextRecall", "timeToFirstToken", "tokensPerSecond"] },
];
